---
- name: Configure Minecraft server
  hosts: minecraft
  become: yes
  vars:
    mc_server_port: 25565
  tasks:
    - name: Update apt cache and install Docker
      apt:
        name: docker.io
        update_cache: yes

    - name: Ensure Docker is started and enabled
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Install pip3
      apt:
        name: python3-pip
        state: present

    - name: Pull Minecraft server Docker image
      command: docker pull itzg/minecraft-server
      register: pull_result
      changed_when: "'Image is up to date' not in pull_result.stdout"

    - name: Remove any existing container with the same name
      command: docker rm -f mc
      ignore_errors: yes
      changed_when: false

    - name: Run Minecraft Docker container
      command: docker run -d --restart unless-stopped --name mc -e EULA=TRUE -p {{ mc_server_port }}:25565 itzg/minecraft-server
      register: container_result
      changed_when: true
